name: Main Workflow

on: [push]

jobs:
  google-formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 # v2 required
      - uses: axel-op/googlejavaformat-action@v3
        with:
          args: "--aosp --replace"
  assembly:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2 # v2 required
      - name: Assembly the app
        run: ./gradlew assembly
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2 # v2 required
      - name: Build the app
        run: ./gradlew build