# Triggers the workflow on every pull request to main branch
on:
  pull_request:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  build-and-test:
    name: Build the standalone app and run tests
    runs-on: ubuntu-latest

    steps:
      - if: github.event_name != 'pull_request'
        uses: actions/checkout@v2
      - if: github.event_name == 'pull_request'
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Build the app with Gradle
        run: ./gradlew app:build

      - name: Run Unit tests with Gradle
        run: ./gradlew test

      - name: Run instrumented tests on emulator with Gradle
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 26
          arch: x86
          disable-animations: true
          script: ./gradlew connectedCheck --stacktrace