# Triggers the workflow on every pull request to main branch
on:
  pull_request:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  build-and-utest:
    name: Build the standalone app and run unit tests
    runs-on: ubuntu-latest

    steps:
      - if: github.event_name != 'pull_request'
        uses: actions/checkout@v2
      - if: github.event_name == 'pull_request'
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Build the app with Gradle
        run: ./gradlew app:build

      - name: Run Unit tests with Gradle
        run: ./gradlew test

  instrumented-tests:
    runs-on: macos-latest   # It is recommended to run this action on a macOS to take advantage of hardware acceleration support provided by HAXM.
    name: Run instrumented tests on emulator with Gradle
    needs: build-and-utest
    strategy:
      matrix:
        api-level: [26, 29]
        target: [default]

    steps:
      - if: github.event_name != 'pull_request'
        uses: actions/checkout@v2
      - if: github.event_name == 'pull_request'
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Run tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: true
          emulator-build: 7425822
          script: ./gradlew connectedCheck --stacktrace